### ISSUE TITLE
allow providing secrets via environment variables

### ISSUE THREAD

**Issue by alarsyo** [prologin/prololo#7]

**Comment by Max1Truc** [comment]
I found two ways of handling this, either :
  - For each secret, like `matrix_password` we can use `#[serde(default = "path")]` with a custom function which provides a value from the environment. However, if neither the env variable nor the config variable are available, we'll get an awful panic message as default functions [aren't supposed to return a Result](https://serde.rs/field-attrs.html#default--path)
  ```
  thread 'main' panicked at 'missing field `matrix_password` or missing environment variable `PROLOLO_MATRIX_PASSWORD`: NotPresent', src/config/defaults.rs:4:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
  - We change the type of fields like `matrix_password` from `T` to `Option<T>`, and handle when these fields are missing "manually", by either replacing them with an env variable, or if the latter is unavailable, return an Err from the main function.

Which way would you recommend, one of them, or another?

**Comment by alarsyo** [comment]
> * For each secret, like `matrix_password` we can use `#[serde(default = "path")]` with a custom function which provides a value from the environment. However, if neither the env variable nor the config variable are available, we'll get an awful panic message as default functions [aren't supposed to return a Result](https://serde.rs/field-attrs.html#default--path)
> 
> 
> ```
> thread 'main' panicked at 'missing field `matrix_password` or missing environment variable `PROLOLO_MATRIX_PASSWORD`: NotPresent', src/config/defaults.rs:4:41
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Panicking isn't too bad for such a service: it can only happen once, during initialization, not while the bot is running. If it happens, our beloved system administrator immediately sees the panic in the logs and can adapt the configuration accordingly. But I'm not a huge fan of coupling deserialization with env var / overriding logic.

> * We change the type of fields like `matrix_password` from `T` to `Option<T>`, and handle when these fields are missing "manually", by either replacing them with an env variable, or if the latter is unavailable, return an Err from the main function.

I had something like this in mind, with clean logic separation: a `YamlConfig` struct that derives `Deserialize`, and then a `ProloloConfig` struct that implements `TryFrom<YamlConfig>`, overriding all values with env vars (with manually written logic... :cry: )

Another solution would be using the [`config`](https://github.com/mehcode/config-rs) crate, which does the overriding logic automagically with proc macros. This might be the best option, if its behaviour follows what we expect.

**Comment by alarsyo** [comment]
Actually, another possibility: this bot only gets deployed on one server, so it doesn't need to support a huge variety of configurations. Maybe we don't need to have secrets in the YAML configuration, and only provide them via env vars. @lportemo what's your input?

**Comment by alarsyo** [comment]
> Je suis d'avis d'avoir toute la conf au meme "endroit"
> Donc autant tout conf en yaml

-- @lportemo on Matrix

Closing this, then. :)
